# Generated by Django 3.1.1 on 2020-10-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201010_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='item',
            name='starting_bid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
