# Generated by Django 3.1.1 on 2020-10-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201010_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
