# Generated by Django 3.1.1 on 2020-10-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bids_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
