# Generated by Django 3.1.1 on 2020-10-11 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201011_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidders', to='auctions.user'),
        ),
    ]
