# Generated by Django 3.1.1 on 2020-10-11 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20201011_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='auctions.item'),
        ),
    ]
