# Generated by Django 3.1.1 on 2020-10-11 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20201011_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='description',
            new_name='comment',
        ),
    ]
